#!/usr/bin/env ruby

require 'rubygems'
require 'robocup'

class Object
  # returns all method names of current object without standard ones
  def m
    if [Module, Class].include? self.class
      public_methods - self.class.public_instance_methods
    else
      class << self
        self.public_instance_methods false
      end
    end
  end
end

module Kernel
  # reloads project
  def reload
    Dir.glob('lib/**/*.rb').each {|file| load file }
  end

  def r
    Robot
  end
end

$:.unshift 'vendor/drbirb/lib'

fork do
  require 'drbirb/loader'
  Client.connect
  Drbirb.server.thread.join
end
sleep 10
require 'drbirbc'