#!/usr/bin/env ruby
require 'robocup'

# TODO: clean up this file

class Object
  # returns all method names of current object without standard ones
  def m
    if [Module, Class].include? self.class
      public_methods - self.class.public_instance_methods
    else
      class << self
        self.public_instance_methods false
      end
    end
  end
end

module Kernel
  # reloads project
  def reload
    Dir.glob('lib/**/*.rb').each {|file| load file }
  end

  def r
    Robot
  end
end

# TODO: remove this horrible hack
$:.unshift 'vendor/drbirb/lib'

pid = fork do
  require 'drbirb/loader'
  Client.connect
  Drbirb.server.thread.join
end
sleep 1
require 'drbirbc'
Process.kill "HUP", pid